#!/bin/bash
# Session Handoff - SessionStart hook
# Reads the latest session snapshot and outputs context for Claude Code
# Generated by Project Jumpstart
#
# This hook is automatically installed by the "Install Hook" button in the
# Session Handoff dashboard card. It runs at the start of each Claude Code
# session and injects the previous session's context.
#
# Requires: sqlite3, jq

INPUT=$(cat)
CWD=$(echo "$INPUT" | jq -r '.cwd // empty')

if [[ -z "$CWD" ]]; then
  exit 0
fi

DB="$HOME/.project-jumpstart/jumpstart.db"

if [[ ! -f "$DB" ]]; then
  exit 0
fi

# Query latest snapshot for this project
SNAPSHOT=$(sqlite3 -separator '|' "$DB" "SELECT s.summary, s.pending_items, s.next_steps, s.git_state, s.files_modified
  FROM session_snapshots s
  JOIN projects p ON s.project_id = p.id
  WHERE p.path = '$CWD'
  ORDER BY s.created_at DESC LIMIT 1" 2>/dev/null)

if [[ -n "$SNAPSHOT" ]]; then
  SUMMARY=$(echo "$SNAPSHOT" | awk -F'|' '{print $1}')
  PENDING=$(echo "$SNAPSHOT" | awk -F'|' '{print $2}')
  NEXT_STEPS=$(echo "$SNAPSHOT" | awk -F'|' '{print $3}')
  GIT_STATE=$(echo "$SNAPSHOT" | awk -F'|' '{print $4}')
  FILES=$(echo "$SNAPSHOT" | awk -F'|' '{print $5}')

  echo "## Session Handoff Context"
  echo ""
  echo "### Previous Session Summary"
  echo "$SUMMARY"
  echo ""

  if [[ "$PENDING" != "[]" && -n "$PENDING" ]]; then
    echo "### Pending Items"
    echo "$PENDING" | jq -r '.[]' 2>/dev/null | while read -r item; do
      echo "- $item"
    done
    echo ""
  fi

  if [[ "$NEXT_STEPS" != "[]" && -n "$NEXT_STEPS" ]]; then
    echo "### Suggested Next Steps"
    echo "$NEXT_STEPS" | jq -r '.[]' 2>/dev/null | while read -r step; do
      echo "- $step"
    done
    echo ""
  fi

  echo "### Git State"
  echo "$GIT_STATE"

  if [[ "$FILES" != "[]" && -n "$FILES" ]]; then
    echo ""
    echo "### Files Modified Last Session"
    echo "$FILES" | jq -r '.[]' 2>/dev/null | while read -r file; do
      echo "- $file"
    done
  fi
fi
